/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Species = IDL.Variant({
  'other' : IDL.Null,
  'feline' : IDL.Null,
  'canine' : IDL.Null,
});
export const Sex = IDL.Variant({
  'female' : IDL.Null,
  'male' : IDL.Null,
  'unknown' : IDL.Null,
});
export const Time = IDL.Int;
export const ToDoItem = IDL.Record({
  'id' : IDL.Nat,
  'description' : IDL.Text,
  'complete' : IDL.Bool,
});
export const SurgeryCase = IDL.Record({
  'id' : IDL.Nat,
  'mrn' : IDL.Text,
  'sex' : Sex,
  'todos' : IDL.Vec(ToDoItem),
  'pdvmNotified' : IDL.Bool,
  'histoComplete' : IDL.Bool,
  'arrivalDate' : Time,
  'presentingComplaint' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'patientLastName' : IDL.Text,
  'labsComplete' : IDL.Bool,
  'patientFirstName' : IDL.Text,
  'imagingComplete' : IDL.Bool,
  'surgeryReportComplete' : IDL.Bool,
  'notes' : IDL.Text,
  'dischargeNotesComplete' : IDL.Bool,
  'breed' : IDL.Text,
  'species' : Species,
  'cultureComplete' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTodoItem' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCase' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Species,
        IDL.Text,
        Sex,
        IDL.Text,
        IDL.Opt(Time),
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'deleteCase' : IDL.Func([IDL.Nat], [], []),
  'deleteTodoItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'exportCases' : IDL.Func([], [IDL.Vec(SurgeryCase)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCase' : IDL.Func([IDL.Nat], [IDL.Opt(SurgeryCase)], ['query']),
  'getCasesBySpecies' : IDL.Func([Species], [IDL.Vec(SurgeryCase)], ['query']),
  'importCases' : IDL.Func([IDL.Vec(SurgeryCase)], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCases' : IDL.Func([], [IDL.Vec(SurgeryCase)], ['query']),
  'toggleCulture' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleDischargeNotes' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleHisto' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleImaging' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleLabs' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'togglePdvmNotified' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleSurgeryReport' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'toggleTodoComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateCase' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        Species,
        IDL.Text,
        Sex,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Bool,
        IDL.Text,
        IDL.Vec(ToDoItem),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Species = IDL.Variant({
    'other' : IDL.Null,
    'feline' : IDL.Null,
    'canine' : IDL.Null,
  });
  const Sex = IDL.Variant({
    'female' : IDL.Null,
    'male' : IDL.Null,
    'unknown' : IDL.Null,
  });
  const Time = IDL.Int;
  const ToDoItem = IDL.Record({
    'id' : IDL.Nat,
    'description' : IDL.Text,
    'complete' : IDL.Bool,
  });
  const SurgeryCase = IDL.Record({
    'id' : IDL.Nat,
    'mrn' : IDL.Text,
    'sex' : Sex,
    'todos' : IDL.Vec(ToDoItem),
    'pdvmNotified' : IDL.Bool,
    'histoComplete' : IDL.Bool,
    'arrivalDate' : Time,
    'presentingComplaint' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'patientLastName' : IDL.Text,
    'labsComplete' : IDL.Bool,
    'patientFirstName' : IDL.Text,
    'imagingComplete' : IDL.Bool,
    'surgeryReportComplete' : IDL.Bool,
    'notes' : IDL.Text,
    'dischargeNotesComplete' : IDL.Bool,
    'breed' : IDL.Text,
    'species' : Species,
    'cultureComplete' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTodoItem' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCase' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Species,
          IDL.Text,
          Sex,
          IDL.Text,
          IDL.Opt(Time),
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'deleteCase' : IDL.Func([IDL.Nat], [], []),
    'deleteTodoItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'exportCases' : IDL.Func([], [IDL.Vec(SurgeryCase)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCase' : IDL.Func([IDL.Nat], [IDL.Opt(SurgeryCase)], ['query']),
    'getCasesBySpecies' : IDL.Func(
        [Species],
        [IDL.Vec(SurgeryCase)],
        ['query'],
      ),
    'importCases' : IDL.Func([IDL.Vec(SurgeryCase)], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCases' : IDL.Func([], [IDL.Vec(SurgeryCase)], ['query']),
    'toggleCulture' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleDischargeNotes' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleHisto' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleImaging' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleLabs' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'togglePdvmNotified' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleSurgeryReport' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'toggleTodoComplete' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateCase' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          Species,
          IDL.Text,
          Sex,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Bool,
          IDL.Text,
          IDL.Vec(ToDoItem),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };