/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Sex = { 'female' : null } |
  { 'male' : null } |
  { 'unknown' : null };
export type Species = { 'other' : null } |
  { 'feline' : null } |
  { 'canine' : null };
export interface SurgeryCase {
  'id' : bigint,
  'mrn' : string,
  'sex' : Sex,
  'todos' : Array<ToDoItem>,
  'pdvmNotified' : boolean,
  'histoComplete' : boolean,
  'arrivalDate' : Time,
  'presentingComplaint' : string,
  'dateOfBirth' : string,
  'patientLastName' : string,
  'labsComplete' : boolean,
  'patientFirstName' : string,
  'imagingComplete' : boolean,
  'surgeryReportComplete' : boolean,
  'notes' : string,
  'dischargeNotesComplete' : boolean,
  'breed' : string,
  'species' : Species,
  'cultureComplete' : boolean,
}
export type Time = bigint;
export interface ToDoItem {
  'id' : bigint,
  'description' : string,
  'complete' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTodoItem' : ActorMethod<[bigint, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCase' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Species,
      string,
      Sex,
      string,
      [] | [Time],
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      string,
      Array<string>,
    ],
    bigint
  >,
  'deleteCase' : ActorMethod<[bigint], undefined>,
  'deleteTodoItem' : ActorMethod<[bigint, bigint], undefined>,
  'exportCases' : ActorMethod<[], Array<SurgeryCase>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCase' : ActorMethod<[bigint], [] | [SurgeryCase]>,
  'getCasesBySpecies' : ActorMethod<[Species], Array<SurgeryCase>>,
  'importCases' : ActorMethod<[Array<SurgeryCase>], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCases' : ActorMethod<[], Array<SurgeryCase>>,
  'toggleCulture' : ActorMethod<[bigint], boolean>,
  'toggleDischargeNotes' : ActorMethod<[bigint], boolean>,
  'toggleHisto' : ActorMethod<[bigint], boolean>,
  'toggleImaging' : ActorMethod<[bigint], boolean>,
  'toggleLabs' : ActorMethod<[bigint], boolean>,
  'togglePdvmNotified' : ActorMethod<[bigint], boolean>,
  'toggleSurgeryReport' : ActorMethod<[bigint], boolean>,
  'toggleTodoComplete' : ActorMethod<[bigint, bigint], undefined>,
  'updateCase' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      Time,
      Species,
      string,
      Sex,
      string,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      boolean,
      string,
      Array<ToDoItem>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];