/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SurgeryCase {
    id: bigint;
    mrn: string;
    sex: Sex;
    todos: Array<ToDoItem>;
    pdvmNotified: boolean;
    histoComplete: boolean;
    arrivalDate: Time;
    presentingComplaint: string;
    dateOfBirth: string;
    patientLastName: string;
    labsComplete: boolean;
    patientFirstName: string;
    imagingComplete: boolean;
    surgeryReportComplete: boolean;
    notes: string;
    dischargeNotesComplete: boolean;
    breed: string;
    species: Species;
    cultureComplete: boolean;
}
export type Time = bigint;
export interface ToDoItem {
    id: bigint;
    description: string;
    complete: boolean;
}
export enum Sex {
    female = "female",
    male = "male",
    femaleSpayed = "femaleSpayed",
    maleNeutered = "maleNeutered",
    unknown_ = "unknown"
}
export enum Species {
    other = "other",
    feline = "feline",
    canine = "canine"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTodoItem(caseId: bigint, description: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCase(mrn: string, patientFirstName: string, patientLastName: string, dateOfBirth: string, species: Species, breed: string, sex: Sex, presentingComplaint: string, arrivalDate: Time | null, dischargeNotesComplete: boolean, pdvmNotified: boolean, labsComplete: boolean, histoComplete: boolean, surgeryReportComplete: boolean, imagingComplete: boolean, cultureComplete: boolean, notes: string, todoDescriptions: Array<string>): Promise<bigint>;
    deleteCase(id: bigint): Promise<void>;
    deleteTodoItem(caseId: bigint, todoId: bigint): Promise<void>;
    exportCases(): Promise<Array<SurgeryCase>>;
    getCallerUserRole(): Promise<UserRole>;
    getCase(id: bigint): Promise<SurgeryCase | null>;
    getCasesBySpecies(species: Species): Promise<Array<SurgeryCase>>;
    importCases(casesArray: Array<SurgeryCase>): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listCases(): Promise<Array<SurgeryCase>>;
    toggleCulture(id: bigint): Promise<boolean>;
    toggleDischargeNotes(id: bigint): Promise<boolean>;
    toggleHisto(id: bigint): Promise<boolean>;
    toggleImaging(id: bigint): Promise<boolean>;
    toggleLabs(id: bigint): Promise<boolean>;
    togglePdvmNotified(id: bigint): Promise<boolean>;
    toggleSurgeryReport(id: bigint): Promise<boolean>;
    toggleTodoComplete(caseId: bigint, todoId: bigint): Promise<void>;
    updateCase(id: bigint, mrn: string, patientFirstName: string, patientLastName: string, dateOfBirth: string, arrivalDate: Time, species: Species, breed: string, sex: Sex, presentingComplaint: string, dischargeNotesComplete: boolean, pdvmNotified: boolean, labsComplete: boolean, histoComplete: boolean, surgeryReportComplete: boolean, imagingComplete: boolean, cultureComplete: boolean, notes: string, todos: Array<ToDoItem>): Promise<void>;
}
import type { Sex as _Sex, Species as _Species, SurgeryCase as _SurgeryCase, Time as _Time, ToDoItem as _ToDoItem, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTodoItem(arg0: bigint, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTodoItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTodoItem(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCase(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Species, arg5: string, arg6: Sex, arg7: string, arg8: Time | null, arg9: boolean, arg10: boolean, arg11: boolean, arg12: boolean, arg13: boolean, arg14: boolean, arg15: boolean, arg16: string, arg17: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCase(arg0, arg1, arg2, arg3, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCase(arg0, arg1, arg2, arg3, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17);
            return result;
        }
    }
    async deleteCase(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCase(arg0);
            return result;
        }
    }
    async deleteTodoItem(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTodoItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTodoItem(arg0, arg1);
            return result;
        }
    }
    async exportCases(): Promise<Array<SurgeryCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.exportCases();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportCases();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCase(arg0: bigint): Promise<SurgeryCase | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCase(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCase(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCasesBySpecies(arg0: Species): Promise<Array<SurgeryCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCasesBySpecies(to_candid_Species_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCasesBySpecies(to_candid_Species_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async importCases(arg0: Array<SurgeryCase>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importCases(to_candid_vec_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importCases(to_candid_vec_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCases(): Promise<Array<SurgeryCase>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCases();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCases();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleCulture(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCulture(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCulture(arg0);
            return result;
        }
    }
    async toggleDischargeNotes(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleDischargeNotes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleDischargeNotes(arg0);
            return result;
        }
    }
    async toggleHisto(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleHisto(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleHisto(arg0);
            return result;
        }
    }
    async toggleImaging(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleImaging(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleImaging(arg0);
            return result;
        }
    }
    async toggleLabs(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLabs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLabs(arg0);
            return result;
        }
    }
    async togglePdvmNotified(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.togglePdvmNotified(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.togglePdvmNotified(arg0);
            return result;
        }
    }
    async toggleSurgeryReport(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSurgeryReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSurgeryReport(arg0);
            return result;
        }
    }
    async toggleTodoComplete(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTodoComplete(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTodoComplete(arg0, arg1);
            return result;
        }
    }
    async updateCase(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Time, arg6: Species, arg7: string, arg8: Sex, arg9: string, arg10: boolean, arg11: boolean, arg12: boolean, arg13: boolean, arg14: boolean, arg15: boolean, arg16: boolean, arg17: string, arg18: Array<ToDoItem>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCase(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCase(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg6), arg7, to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg8), arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16, arg17, arg18);
            return result;
        }
    }
}
function from_candid_Sex_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sex): Sex {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Species_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Species): Species {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_SurgeryCase_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SurgeryCase): SurgeryCase {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SurgeryCase]): SurgeryCase | null {
    return value.length === 0 ? null : from_candid_SurgeryCase_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mrn: string;
    sex: _Sex;
    todos: Array<_ToDoItem>;
    pdvmNotified: boolean;
    histoComplete: boolean;
    arrivalDate: _Time;
    presentingComplaint: string;
    dateOfBirth: string;
    patientLastName: string;
    labsComplete: boolean;
    patientFirstName: string;
    imagingComplete: boolean;
    surgeryReportComplete: boolean;
    notes: string;
    dischargeNotesComplete: boolean;
    breed: string;
    species: _Species;
    cultureComplete: boolean;
}): {
    id: bigint;
    mrn: string;
    sex: Sex;
    todos: Array<ToDoItem>;
    pdvmNotified: boolean;
    histoComplete: boolean;
    arrivalDate: Time;
    presentingComplaint: string;
    dateOfBirth: string;
    patientLastName: string;
    labsComplete: boolean;
    patientFirstName: string;
    imagingComplete: boolean;
    surgeryReportComplete: boolean;
    notes: string;
    dischargeNotesComplete: boolean;
    breed: string;
    species: Species;
    cultureComplete: boolean;
} {
    return {
        id: value.id,
        mrn: value.mrn,
        sex: from_candid_Sex_n11(_uploadFile, _downloadFile, value.sex),
        todos: value.todos,
        pdvmNotified: value.pdvmNotified,
        histoComplete: value.histoComplete,
        arrivalDate: value.arrivalDate,
        presentingComplaint: value.presentingComplaint,
        dateOfBirth: value.dateOfBirth,
        patientLastName: value.patientLastName,
        labsComplete: value.labsComplete,
        patientFirstName: value.patientFirstName,
        imagingComplete: value.imagingComplete,
        surgeryReportComplete: value.surgeryReportComplete,
        notes: value.notes,
        dischargeNotesComplete: value.dischargeNotesComplete,
        breed: value.breed,
        species: from_candid_Species_n13(_uploadFile, _downloadFile, value.species),
        cultureComplete: value.cultureComplete
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
} | {
    femaleSpayed: null;
} | {
    maleNeutered: null;
} | {
    unknown: null;
}): Sex {
    return "female" in value ? Sex.female : "male" in value ? Sex.male : "femaleSpayed" in value ? Sex.femaleSpayed : "maleNeutered" in value ? Sex.maleNeutered : "unknown" in value ? Sex.unknown : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    feline: null;
} | {
    canine: null;
}): Species {
    return "other" in value ? Species.other : "feline" in value ? Species.feline : "canine" in value ? Species.canine : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SurgeryCase>): Array<SurgeryCase> {
    return value.map((x)=>from_candid_SurgeryCase_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Sex_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sex): _Sex {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Species_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Species): _Species {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_SurgeryCase_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SurgeryCase): _SurgeryCase {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mrn: string;
    sex: Sex;
    todos: Array<ToDoItem>;
    pdvmNotified: boolean;
    histoComplete: boolean;
    arrivalDate: Time;
    presentingComplaint: string;
    dateOfBirth: string;
    patientLastName: string;
    labsComplete: boolean;
    patientFirstName: string;
    imagingComplete: boolean;
    surgeryReportComplete: boolean;
    notes: string;
    dischargeNotesComplete: boolean;
    breed: string;
    species: Species;
    cultureComplete: boolean;
}): {
    id: bigint;
    mrn: string;
    sex: _Sex;
    todos: Array<_ToDoItem>;
    pdvmNotified: boolean;
    histoComplete: boolean;
    arrivalDate: _Time;
    presentingComplaint: string;
    dateOfBirth: string;
    patientLastName: string;
    labsComplete: boolean;
    patientFirstName: string;
    imagingComplete: boolean;
    surgeryReportComplete: boolean;
    notes: string;
    dischargeNotesComplete: boolean;
    breed: string;
    species: _Species;
    cultureComplete: boolean;
} {
    return {
        id: value.id,
        mrn: value.mrn,
        sex: to_candid_Sex_n5(_uploadFile, _downloadFile, value.sex),
        todos: value.todos,
        pdvmNotified: value.pdvmNotified,
        histoComplete: value.histoComplete,
        arrivalDate: value.arrivalDate,
        presentingComplaint: value.presentingComplaint,
        dateOfBirth: value.dateOfBirth,
        patientLastName: value.patientLastName,
        labsComplete: value.labsComplete,
        patientFirstName: value.patientFirstName,
        imagingComplete: value.imagingComplete,
        surgeryReportComplete: value.surgeryReportComplete,
        notes: value.notes,
        dischargeNotesComplete: value.dischargeNotesComplete,
        breed: value.breed,
        species: to_candid_Species_n3(_uploadFile, _downloadFile, value.species),
        cultureComplete: value.cultureComplete
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Species): {
    other: null;
} | {
    feline: null;
} | {
    canine: null;
} {
    return value == Species.other ? {
        other: null
    } : value == Species.feline ? {
        feline: null
    } : value == Species.canine ? {
        canine: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sex): {
    female: null;
} | {
    male: null;
} | {
    femaleSpayed: null;
} | {
    maleNeutered: null;
} | {
    unknown: null;
} {
    return value == Sex.female ? {
        female: null
    } : value == Sex.male ? {
        male: null
    } : value == Sex.femaleSpayed ? {
        femaleSpayed: null
    } : value == Sex.maleNeutered ? {
        maleNeutered: null
    } : value == Sex.unknown ? {
        unknown_: null
    } : value;
}
function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SurgeryCase>): Array<_SurgeryCase> {
    return value.map((x)=>to_candid_SurgeryCase_n19(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
